name: Publish Packages

on:
  push:
    branches: [ "main" ]       
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

    # - name: Publish Spoleto.SMS to Nuget
    #   uses: alirezanet/publish-nuget@v3.0.4
    #   with:
    #       # Filepath of the project to be packaged, relative to root of repository
    #       PROJECT_FILE_PATH: src/Spoleto.Sms.Providers/Spoleto.Sms.Providers.csproj
    #       # API key to authenticate with NuGet server
    #       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #       # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
    #       INCLUDE_SYMBOLS: true
    #       # Flag to toggle git tagging, enabled by default
    #       TAG_COMMIT: false

      - name: Pack Spoleto.SMS
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Spoleto.SMS/Spoleto.SMS.csproj -o .
      - name: Pack Spoleto.SMS.GetSms
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Providers/Spoleto.SMS.GetSms/Spoleto.SMS.GetSms.csproj -o .
      - name: Pack Spoleto.SMS.Smsc
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Providers/Spoleto.SMS.Smsc/Spoleto.SMS.Smsc.csproj -o .

      - name: Pack Spoleto.SMS.Extensions.Messaging
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Extensions/Spoleto.SMS.Extensions.Messaging/Spoleto.SMS.Extensions.Messaging.csproj -o .
      - name: Pack Spoleto.SMS.Extensions.GetSms
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Extensions/Spoleto.SMS.Extensions.GetSms/Spoleto.SMS.Extensions.GetSms.csproj -o .
      - name: Pack Spoleto.SMS.Extensions.Smsc
        run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release src/Extensions/Spoleto.SMS.Extensions.Smsc/Spoleto.SMS.Extensions.Smsc.csproj -o .

      - name: Push packages
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload assets to release
        run: |
          chmod +x ./publish-assets-to-github.sh
          ./publish-assets-to-github.sh ${{ github.event.release.tag_name }}

