name: Build

on:
  push:
    branches: [ "main" ]    
  pull_request:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
    - uses: actions/checkout@v6
        
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal
